import SwiftSyntax
import SwiftSyntaxBuilder

public struct NoDepSourceFactory {
    let mockClassFactory: NoDepMockClassFactory

    public init(
        mockClassFactory: NoDepMockClassFactory = NoDepMockClassFactory()
    ) {
        self.mockClassFactory = mockClassFactory
    }

    public func classDecl(
        protocolDecl: ProtocolDeclSyntax,
        surroundWithPoundIfDebug: Bool,
        importDeclsToCopy: [ImportDeclSyntax]
    ) throws -> some SyntaxProtocol {
        let classDecl = try mockClassFactory.classDecl(
            protocolDecl: protocolDecl
        )
        return SourceFileSyntax {
            for importDecl in importDeclsToCopy {
                importDecl
            }

            if surroundWithPoundIfDebug {
                IfConfigDeclSyntax(
                    clauses: IfConfigClauseListSyntax(itemsBuilder: {
                        IfConfigClauseSyntax(
                            poundKeyword: .poundIfToken(),
                            condition: DeclReferenceExprSyntax(baseName: .identifier("DEBUG")),
                            elements: .decls(MemberBlockItemListSyntax(itemsBuilder: {

                                MemberBlockItemSyntax(decl: classDecl)
                            }))
                        )
                    })
                )
                .with(\.leadingTrivia, .newlines(2))
            } else {
                classDecl
            }
        }
        .with(
            \.leadingTrivia,
            [
                .docLineComment("// BEGIN swift-mock-gen"),
                .newlines(1),
                .docLineComment("// DO NOT EDIT. This mock class is generated by swift-mock-gen."),
                .newlines(1)
            ]
        )
        .with(
            \.trailingTrivia,
             [
                .docLineComment("// END swift-mock-gen")
             ]
        )
    }
}
