name: Build and test

on:
  push:
    branches: [ main, public ]
  pull_request:
    branches: [ main, public ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Swift environment
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 'latest'

    - name: Build
      run: swift build

    - name: Test
      run: swift test